In [12]:
import datasets
import huggingface_hub
import matplotlib.pyplot as plt
import transformers
import pandas as pd

In [13]:
import torch
print(f"PyTorch version: {torch.__version__}")

x = torch.rand(5, 3)
print("Random tensor:\n", x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if torch.cuda.is_available():
    print(f"GPU count: {torch.cuda.device_count()}")
    print(f"Current GPU: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.10.0+cu126
Random tensor:
 tensor([[0.7854, 0.2384, 0.3555],
        [0.1578, 0.4202, 0.4193],
        [0.5858, 0.7221, 0.7184],
        [0.8489, 0.7527, 0.9912],
        [0.0636, 0.7476, 0.5768]])
Using device: cuda
GPU count: 1
Current GPU: NVIDIA GeForce RTX 4060 Laptop GPU

In [14]:
from transformers import pipeline
classifier = pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [15]:
text = """ code geass is one of those series that everybody recomends and once you watch it you know why.

Mechas, war, romance, comedy, rivality, unexpected twsits, explotions, mindgames and more mechas! what else do you want!!! xD it totally deserver its place as one of the best animes ever made.

the only aspect i see as a flaw is the art with a 9/10 the people seem a little bit deformed or too skinny but once you get use to it is great!.The user wants freedom.

and it has by far the best story i have ever seen you just get hooked to it from the second episode and cant stop until finishing it.

almost perfect serie, recomended to anyone who is a human beeing (nevermind, my dog liked it) """

In [16]:
classifier(text)

[{'label': 'POSITIVE', 'score': 0.9967235922813416}]

In [17]:
text1 = "Narendra Modi is prime minister of India"

In [18]:
NER = pipeline('ner', aggregation_strategy='simple')
out = NER(text1)
print(pd.DataFrame(out))

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cuda:0

  entity_group     score           word  start  end
0          PER  0.998214  Narendra Modi      0   13
1          LOC  0.997805          India     35   40

In [19]:
text2 = "I see myself CEO of Google LLC. I will earn in millions"
out = NER(text2)
print(pd.DataFrame(out))

  entity_group     score        word  start  end
0          ORG  0.998921  Google LLC     20   30

In [20]:
text3 = "The company Google is headquartered in Mountain View, California."
out = NER(text3)
print(pd.DataFrame(out))

  entity_group     score           word  start  end
0          ORG  0.998703         Google     12   18
1          LOC  0.995206  Mountain View     39   52
2          LOC  0.997912     California     54   64

In [21]:
print(out)

[{'entity_group': 'ORG', 'score': np.float32(0.9987025), 'word': 'Google', 'start': 12, 'end': 18}, {'entity_group': 'LOC', 'score': np.float32(0.99520624), 'word': 'Mountain View', 'start': 39, 'end': 52}, {'entity_group': 'LOC', 'score': np.float32(0.99791247), 'word': 'California', 'start': 54, 'end': 64}]

In [22]:
reader = pipeline('question-answering')
question = 'what does user want ?'
outputs = reader(question=question, context= text)
pd.DataFrame([outputs])

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

      score  start  end   answer
0  0.932237    450  457  freedom

In [23]:
summarizer = pipeline('summarization')
outputs = summarizer(text, clean_up_tokenization_spaces=True, max_length=90)
print(outputs[0]['summary_text'])

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

 The only aspect i see as a flaw is the art with a 9/10 the people seem a little bit deformed or too skinny but once you get use to it is great. The almost perfect serie, recomended to anyone who is a human beeing (nevermind, my dog liked it)

In [24]:
translate = pipeline('translation_en_to_de', model='Helsinki-NLP/opus-mt-en-de')
output = translate(text, clean_up_tokenization_spaces=True, min_length=120)
print(output[0]['translation_text'])
print(len(output[0]['translation_text']))

/home/aman/miniconda3/envs/campusx/lib/python3.10/site-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Device set to use cuda:0

Code Geass ist eine jener Serien, die jeder recomends und sobald Sie es sehen Sie wissen, warum. Mechas, Krieg, Romantik, Komödie, Rivalität, unerwartete Twsits, Explotionen, Mindgames und mehr mechas! was sonst wollen Sie! xD es völlig verdient seinen Platz als einer der besten Animes jemals gemacht. der einzige Aspekt, den ich als Fehler sehe, ist die Kunst mit einem 9/10 die Menschen scheinen ein wenig verformt oder zu dünn, aber wenn Sie es nutzen ist toll!.Der Benutzer will Freiheit. und es hat bei weitem die beste Geschichte, die ich je gesehen habe, Sie nur an sie von der zweiten Folge und Cant Stop bis zum Ende. fast perfekt serie, recomended zu jedem, der ein Mensch ist Bienen (Nevermind, mein Hund mochte es)
727

In [25]:
translate = pipeline('translation_en_to_de', model='Helsinki-NLP/opus-mt-en-de')
output = translate(text, clean_up_tokenization_spaces=False, min_length=120)
print(output[0]['translation_text'])
print(len(output[0]['translation_text']))

Device set to use cuda:0

Code Geass ist eine jener Serien, die jeder recomends und sobald Sie es sehen Sie wissen, warum. Mechas, Krieg, Romantik, Komödie, Rivalität, unerwartete Twsits, Explotionen, Mindgames und mehr mechas! was sonst wollen Sie! xD es völlig verdient seinen Platz als einer der besten Animes jemals gemacht. der einzige Aspekt, den ich als Fehler sehe, ist die Kunst mit einem 9/10 die Menschen scheinen ein wenig verformt oder zu dünn, aber wenn Sie es nutzen ist toll!.Der Benutzer will Freiheit. und es hat bei weitem die beste Geschichte, die ich je gesehen habe, Sie nur an sie von der zweiten Folge und Cant Stop bis zum Ende. fast perfekt serie, recomended zu jedem, der ein Mensch ist Bienen (Nevermind, mein Hund mochte es)
727

In [26]:
from huggingface_hub import list_datasets
all_datasets = list(list_datasets(limit=100))
print(f"There are total {len(all_datasets)} datasets (limited)")
print(f"Some example datasets are {all_datasets[:5]}")

There are total 100 datasets (limited)
Some example datasets are [DatasetInfo(id='openbmb/UltraData-Math', author='openbmb', sha='642faf937ef942e0c45b15ec37f33884ff43d369', created_at=datetime.datetime(2026, 1, 14, 12, 17, 26, tzinfo=datetime.timezone.utc), last_modified=datetime.datetime(2026, 2, 10, 3, 18, 19, tzinfo=datetime.timezone.utc), private=False, gated=False, disabled=False, downloads=34974, downloads_all_time=None, likes=227, paperswithcode_id=None, tags=['task_categories:text-generation', 'language:en', 'language:zh', 'license:apache-2.0', 'size_categories:100M<n<1B', 'format:parquet', 'modality:text', 'library:datasets', 'library:dask', 'library:polars', 'library:mlcroissant', 'region:us', 'llm', 'pretraining', 'math', 'data-synthesis', 'data-filtering', 'high-quality', 'mathematical-reasoning'], trending_score=63, card_data=None, siblings=None, xet_enabled=None), DatasetInfo(id='ma-xu/fine-t2i', author='ma-xu', sha='f799046f995af992596336c360319e7cb7e5c2bb', created_at=datetime.datetime(2026, 1, 15, 6, 4, tzinfo=datetime.timezone.utc), last_modified=datetime.datetime(2026, 2, 17, 2, 15, 1, tzinfo=datetime.timezone.utc), private=False, gated=False, disabled=False, downloads=22561, downloads_all_time=None, likes=69, paperswithcode_id=None, tags=['task_categories:image-to-text', 'task_categories:text-to-image', 'language:en', 'license:apache-2.0', 'size_categories:100K<n<1M', 'format:webdataset', 'modality:image', 'modality:text', 'library:datasets', 'library:webdataset', 'library:mlcroissant', 'arxiv:2602.09439', 'region:us', 'text', 'image', 'image-generation', 't2i', 'image caption'], trending_score=61, card_data=None, siblings=None, xet_enabled=None), DatasetInfo(id='OpenMed/Medical-Reasoning-SFT-Mega', author='OpenMed', sha='7adced6ff1fa04a6b022932ef25c71e56011fed9', created_at=datetime.datetime(2026, 2, 6, 14, 52, 54, tzinfo=datetime.timezone.utc), last_modified=datetime.datetime(2026, 2, 6, 15, 6, 13, tzinfo=datetime.timezone.utc), private=False, gated=False, disabled=False, downloads=1466, downloads_all_time=None, likes=75, paperswithcode_id=None, tags=['task_categories:text-generation', 'task_categories:question-answering', 'language:en', 'license:apache-2.0', 'size_categories:1M<n<10M', 'format:parquet', 'format:optimized-parquet', 'modality:text', 'library:datasets', 'library:dask', 'library:polars', 'library:mlcroissant', 'region:us', 'medical', 'reasoning', 'healthcare', 'clinical', 'chain-of-thought', 'thinking', 'sft', 'mega', 'combined'], trending_score=54, card_data=None, siblings=None, xet_enabled=None), DatasetInfo(id='GD-ML/IntTravel_dataset', author='GD-ML', sha='becc4f42df1a929b685f59f3574fc0270a59c59b', created_at=datetime.datetime(2026, 2, 11, 6, 33, 51, tzinfo=datetime.timezone.utc), last_modified=datetime.datetime(2026, 2, 18, 13, 49, 59, tzinfo=datetime.timezone.utc), private=False, gated=False, disabled=False, downloads=525, downloads_all_time=None, likes=54, paperswithcode_id=None, tags=['region:us'], trending_score=54, card_data=None, siblings=None, xet_enabled=None), DatasetInfo(id='nvidia/SAGE-10k', author='nvidia', sha='d425de49ff445fd3903d790a11461d23ffd0c7dd', created_at=datetime.datetime(2025, 12, 31, 5, 16, 57, tzinfo=datetime.timezone.utc), last_modified=datetime.datetime(2026, 2, 11, 3, 54, 29, tzinfo=datetime.timezone.utc), private=False, gated=False, disabled=False, downloads=8599, downloads_all_time=None, likes=52, paperswithcode_id=None, tags=['task_categories:text-to-3d', 'language:en', 'license:apache-2.0', 'size_categories:10K<n<100K', 'arxiv:2602.10116', 'region:us', 'Scene-Generation', 'Interactive-Scenes', 'Embodied-AI', 'Scene-Understanding', 'Robotics'], trending_score=49, card_data=None, siblings=None, xet_enabled=None)]

In [27]:
from datasets import load_dataset
emotion_dataset = load_dataset('emotion')
emotion_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [28]:
train_datset = emotion_dataset['train']
train_datset

Dataset({
    features: ['text', 'label'],
    num_rows: 16000
})

In [29]:
train_datset[0]
train_datset[:5]

{'text': ['i didnt feel humiliated',
  'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
  'im grabbing a minute to post i feel greedy wrong',
  'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
  'i am feeling grouchy'],
 'label': [0, 0, 3, 2, 3]}

In [30]:
train_datset.column_names

['text', 'label']

In [31]:
train_datset.features

{'text': Value('string'),
 'label': ClassLabel(names=['sadness', 'joy', 'love', 'anger', 'fear', 'surprise'])}

In [32]:
train_datset.features
train_datset.features['label'].names

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [33]:
emotion_dataset.set_format(type='pandas')
df = emotion_dataset['train'][:]
df.head()

                                                text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3
3  i am ever feeling nostalgic about the fireplac...      2
4                               i am feeling grouchy      3

In [34]:
emotion_dataset['train'].features['label'].int2str(5)

'surprise'

In [35]:
def label_2_str(row):
    return emotion_dataset['train'].features['label'].int2str(row)

df['label_name'] = df['label'].apply(label_2_str)
df.head

<bound method NDFrame.head of                                                     text  label label_name
0                                i didnt feel humiliated      0    sadness
1      i can go from feeling so hopeless to so damned...      0    sadness
2       im grabbing a minute to post i feel greedy wrong      3      anger
3      i am ever feeling nostalgic about the fireplac...      2       love
4                                   i am feeling grouchy      3      anger
...                                                  ...    ...        ...
15995  i just had a very brief time in the beanbag an...      0    sadness
15996  i am now turning and i feel pathetic that i am...      0    sadness
15997                     i feel strong and good overall      1        joy
15998  i feel like this was such a rude comment and i...      3      anger
15999  i know a lot but i feel so stupid because i ca...      0    sadness

[16000 rows x 3 columns]>

In [36]:
emotion_dataset.reset_format()

In [37]:
from transformers import AutoTokenizer
model = 'distilbert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model)

In [58]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__bool__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_tokens',
 '_auto_class',
 '_batch_encode_plus',
 '_call_one',
 '_convert_encoding',
 '_convert_id_to_token',
 '_convert_token_to_id_with_added_voc',
 '_create_repo',
 '_decode',
 '_decode_use_source_tokenizer',
 '_encode_plus',
 '_eventual_warn_about_too_long_sequence',
 '_eventually_correct_t5_max_length',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_pad',
 '_pad_token_type_id',
 '_patch_mistral_regex',
 '_processor_class',
 '_save_pretrained',
 '_set_model_specific_special_tokens',
 '_set_processor_class',
 '_special_tokens_map',
 '_switch_to_input_mode',
 '_switch_to_target_mode',
 '_tokenizer',
 '_upload_modified_files',
 'add_prefix_space',
 'add_special_tokens',
 'add_tokens',
 'added_tokens_decoder',
 'added_tokens_encoder',
 'all_special_ids',
 'all_special_tokens',
 'all_special_tokens_extended',
 'apply_chat_template',
 'as_target_tokenizer',
 'backend_tokenizer',
 'batch_decode',
 'batch_encode_plus',
 'build_inputs_with_special_tokens',
 'can_save_slow_tokenizer',
 'chat_template',
 'clean_up_tokenization',
 'clean_up_tokenization_spaces',
 'convert_added_tokens',
 'convert_ids_to_tokens',
 'convert_tokens_to_ids',
 'convert_tokens_to_string',
 'create_token_type_ids_from_sequences',
 'decode',
 'decoder',
 'deprecation_warnings',
 'do_lower_case',
 'encode',
 'encode_message_with_chat_template',
 'encode_plus',
 'extra_special_tokens',
 'from_pretrained',
 'get_added_vocab',
 'get_chat_template',
 'get_special_tokens_mask',
 'get_vocab',
 'init_inputs',
 'init_kwargs',
 'is_fast',
 'max_len_sentences_pair',
 'max_len_single_sentence',
 'model_input_names',
 'model_max_length',
 'name_or_path',
 'num_special_tokens_to_add',
 'pad',
 'pad_token_type_id',
 'padding_side',
 'prepare_for_model',
 'prepare_seq2seq_batch',
 'pretrained_vocab_files_map',
 'push_to_hub',
 'register_for_auto_class',
 'sanitize_special_tokens',
 'save_chat_templates',
 'save_pretrained',
 'save_vocabulary',
 'set_truncation_and_padding',
 'slow_tokenizer_class',
 'special_tokens_map',
 'special_tokens_map_extended',
 'split_special_tokens',
 'tokenize',
 'train_new_from_iterator',
 'truncate_sequences',
 'truncation_side',
 'verbose',
 'vocab',
 'vocab_files_names',
 'vocab_size']

In [38]:
text = 'My favourite food is Masala Dosa'
encoded_text = tokenizer(text)
print(encoded_text)

{'input_ids': [101, 2026, 8837, 2833, 2003, 16137, 7911, 9998, 2050, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [39]:
type(encoded_text)

transformers.tokenization_utils_base.BatchEncoding

In [40]:
tokens = tokenizer.convert_ids_to_tokens(encoded_text.input_ids)
print(tokens)

['[CLS]', 'my', 'favourite', 'food', 'is', 'mas', '##ala', 'dos', '##a', '[SEP]']

In [41]:
string = tokenizer.convert_tokens_to_string(tokens)
print(string)

[CLS] my favourite food is masala dosa [SEP]

In [42]:
tokenizer.vocab_size, tokenizer.model_max_length, tokenizer.model_input_names

(30522, 512, ['input_ids', 'attention_mask'])

In [43]:
emotion_dataset['train'][:2]

{'text': ['i didnt feel humiliated',
  'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'],
 'label': [0, 0]}

In [44]:
def tokenization(batch):
    return tokenizer(batch['text'], padding = True, truncation = True, return_tensors='np')

tokenization(emotion_dataset['train'][:2])

{'input_ids': array([[  101,  1045,  2134,  2102,  2514, 26608,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0],
       [  101,  1045,  2064,  2175,  2013,  3110,  2061, 20625,  2000,
         2061,  9636, 17772,  2074,  2013,  2108,  2105,  2619,  2040,
        14977,  1998,  2003,  8300,   102]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]])}

In [45]:
emotions_encoded = emotion_dataset.map(tokenization, batched=True, batch_size=None)
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 2000
    })
})

In [46]:
input = emotions_encoded['train'][:1]['input_ids']
print(f"Seq length: {len(input[0])}")

Seq length: 87

In [47]:
from transformers import AutoModel
model_name = 'distilbert-base-uncased'
model = AutoModel.from_pretrained(model_name)

In [51]:
ex_text = 'this is a text document'
inputs = tokenizer(ex_text, return_tensors='pt')
print(inputs)

{'input_ids': tensor([[ 101, 2023, 2003, 1037, 3793, 6254,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [53]:
outputs = model(**inputs)
outputs

BaseModelOutput(last_hidden_state=tensor([[[-0.2561, -0.1391,  0.0405,  ..., -0.2022,  0.2370,  0.4425],
         [-0.6480, -0.2883, -0.1718,  ..., -0.4260,  0.6918,  0.2506],
         [-0.5226, -0.1469,  0.1628,  ..., -0.2631,  0.2028,  0.8833],
         ...,
         [ 0.1927,  0.0911,  0.3891,  ..., -0.4208,  0.1865, -0.0111],
         [-0.0330, -0.2848, -0.0822,  ..., -0.1205,  0.0785, -0.0624],
         [ 0.8464,  0.1025, -0.5195,  ...,  0.1458, -0.7754, -0.1925]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [57]:
print(outputs.last_hidden_state.shape)

torch.Size([1, 7, 768])

In [56]:
inputs['input_ids'].shape

torch.Size([1, 7])